// __fixtures__.js – Inventory feature sample/mock data for DEV-only usage.
// This file is auto-generated by refactoring. Do not add imports or logic here.

// InventoryDashboard
export const SAMPLE_STATS = {
  total_items: 142,
  low_stock_count: 18,
  total_value: 2340000,
  pending_pos: 7,
};

// InventoryDashboard
export const SAMPLE_SUMMARY = [
  { category: 'Raw Materials', total_quantity: 850, item_count: 42 },
  { category: 'Finished Goods', total_quantity: 340, item_count: 28 },
  { category: 'Packaging',     total_quantity: 1200, item_count: 15 },
  { category: 'Consumables',   total_quantity: 500, item_count: 30 },
  { category: 'Spares',        total_quantity: 210, item_count: 27 },
];

// InventoryDashboard
export const SAMPLE_LOW = [
  { id: 1, name: 'Ball Bearings 20mm', sku: 'SKU-001', category: 'Spares', current_stock: 5, reorder_level: 20, unit: 'pcs' },
  { id: 2, name: 'Packing Tape 48mm', sku: 'SKU-012', category: 'Packaging', current_stock: 12, reorder_level: 50, unit: 'rolls' },
  { id: 3, name: 'Lubricant Oil 5L',  sku: 'SKU-034', category: 'Consumables', current_stock: 2, reorder_level: 10, unit: 'cans' },
  { id: 4, name: 'Copper Wire 2.5mm', sku: 'SKU-056', category: 'Raw Materials', current_stock: 30, reorder_level: 100, unit: 'kg' },
];

// InventoryDashboard (renamed from SAMPLE_MOVES to avoid clash with StockMovements)
export const SAMPLE_MOVES_DASHBOARD = [
  { id: 1, item_name: 'Ball Bearings 20mm', movement_type: 'IN',  quantity: 200, reference: 'GRN-001', created_at: new Date().toISOString() },
  { id: 2, item_name: 'Packing Tape 48mm',  movement_type: 'OUT', quantity: 50,  reference: 'SO-102',  created_at: new Date().toISOString() },
  { id: 3, item_name: 'Lubricant Oil 5L',   movement_type: 'OUT', quantity: 5,   reference: 'ISS-007', created_at: new Date().toISOString() },
  { id: 4, item_name: 'Copper Wire 2.5mm',  movement_type: 'IN',  quantity: 500, reference: 'PO-045',  created_at: new Date().toISOString() },
];

// ItemMaster (renamed from SAMPLE_ITEMS to avoid clash with StockMovements)
export const SAMPLE_ITEMS_ITEMMASTER = [
  { id: 1, sku: 'SKU-001', name: 'Ball Bearings 20mm', category: 'Spares',        unit: 'pcs',  current_stock: 5,   reorder_level: 20,  unit_price: 45,   is_active: true },
  { id: 2, sku: 'SKU-002', name: 'Copper Wire 2.5mm',  category: 'Raw Materials', unit: 'kg',   current_stock: 280, reorder_level: 100, unit_price: 620,  is_active: true },
  { id: 3, sku: 'SKU-003', name: 'Packing Tape 48mm',  category: 'Packaging',     unit: 'rolls',current_stock: 12,  reorder_level: 50,  unit_price: 35,   is_active: true },
  { id: 4, sku: 'SKU-004', name: 'Lubricant Oil 5L',   category: 'Consumables',   unit: 'cans', current_stock: 2,   reorder_level: 10,  unit_price: 850,  is_active: true },
  { id: 5, sku: 'SKU-005', name: 'Steel Rods 12mm',    category: 'Raw Materials', unit: 'kg',   current_stock: 600, reorder_level: 200, unit_price: 92,   is_active: true },
  { id: 6, sku: 'SKU-006', name: 'Carton Box 40x30',   category: 'Packaging',     unit: 'pcs',  current_stock: 850, reorder_level: 300, unit_price: 28,   is_active: true },
];

// StockMovements (renamed from SAMPLE_MOVES to avoid clash with InventoryDashboard)
export const SAMPLE_MOVES_STOCK = [
  { id: 1, item_name: 'Steel Rods 12mm',    sku: 'SKU-005', movement_type: 'IN',  quantity: 500, reference: 'GRN-001', notes: 'Receipt against PO-001', created_at: '2024-11-01T09:00:00Z', created_by: 'Rajesh K' },
  { id: 2, item_name: 'Ball Bearings 20mm', sku: 'SKU-001', movement_type: 'OUT', quantity: 50,  reference: 'SO-102',  notes: 'Issued for production',   created_at: '2024-11-02T11:30:00Z', created_by: 'Priya S' },
  { id: 3, item_name: 'Packing Tape 48mm',  sku: 'SKU-003', movement_type: 'OUT', quantity: 30,  reference: 'ISS-007', notes: 'Dispatch packaging',        created_at: '2024-11-03T14:00:00Z', created_by: 'Anand M' },
  { id: 4, item_name: 'Lubricant Oil 5L',   sku: 'SKU-004', movement_type: 'IN',  quantity: 20,  reference: 'GRN-002', notes: 'Monthly restock',          created_at: '2024-11-05T10:00:00Z', created_by: 'Rajesh K' },
  { id: 5, item_name: 'Copper Wire 2.5mm',  sku: 'SKU-002', movement_type: 'IN',  quantity: 200, reference: 'GRN-003', notes: 'Received from Tata',        created_at: '2024-11-07T09:30:00Z', created_by: 'Priya S' },
  { id: 6, item_name: 'Steel Rods 12mm',    sku: 'SKU-005', movement_type: 'OUT', quantity: 80,  reference: 'WO-011',  notes: 'Work order issue',          created_at: '2024-11-08T15:00:00Z', created_by: 'Anand M' },
];

// StockMovements (renamed from SAMPLE_ITEMS to avoid clash with ItemMaster)
export const SAMPLE_ITEMS_STOCK = [
  { id: 1, name: 'Steel Rods 12mm',    sku: 'SKU-005' },
  { id: 2, name: 'Ball Bearings 20mm', sku: 'SKU-001' },
  { id: 3, name: 'Packing Tape 48mm',  sku: 'SKU-003' },
  { id: 4, name: 'Lubricant Oil 5L',   sku: 'SKU-004' },
  { id: 5, name: 'Copper Wire 2.5mm',  sku: 'SKU-002' },
];
