/**
 * Manifest Analyzer — report formatting helpers.
 * Pure functions: given data, return strings. No IO here.
 */

export const h1 = (t) => `# ${t}\n`;
export const h2 = (t) => `\n## ${t}\n`;
export const h3 = (t) => `\n### ${t}\n`;

export const stamp = () =>
  `> Generated by **Manifest Analyzer** on ${new Date().toISOString()}.\n` +
  `> Read-only analysis — no application source was modified.\n`;

/** Render a markdown table. `rows` is an array of arrays. */
export function table(headers, rows) {
  if (!rows.length) return '_None found._\n';
  const esc = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const lines = [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((r) => `| ${r.map(esc).join(' | ')} |`),
  ];
  return `${lines.join('\n')}\n`;
}

export function bulletList(items) {
  if (!items.length) return '_None._\n';
  return `${items.map((i) => `- ${i}`).join('\n')}\n`;
}

/** ASCII bar for the dependency heatmap (step 12). */
export function bar(value, max, width = 24, char = '█') {
  if (max <= 0) return '';
  const n = Math.max(value > 0 ? 1 : 0, Math.round((value / max) * width));
  return char.repeat(n);
}

export const pct = (n, d) => (d ? Math.round((n / d) * 100) : 0);

/** Fixed-width text-report section. */
export function section(title, body) {
  return `\n${'-'.repeat(78)}\n${title}\n${'-'.repeat(78)}\n${body}\n`;
}

/** Score → letter rating used across the health report and dashboard. */
export function rating(score) {
  if (score >= 85) return 'Excellent';
  if (score >= 70) return 'Good';
  if (score >= 50) return 'Average';
  return 'Needs Attention';
}

export const ratingClass = (score) =>
  score >= 85 ? 'excellent' : score >= 70 ? 'good' : score >= 50 ? 'average' : 'poor';

/** Clamp a computed score into 0..100 and round. */
export const clampScore = (n) => Math.max(0, Math.min(100, Math.round(n)));

export const escapeHtml = (s) =>
  String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

/** Mermaid node ids must be alphanumeric-ish; labels go in brackets. */
export const mermaidId = (s) => String(s).replace(/[^A-Za-z0-9]/g, '_');
