/**
 * Suite 09 — Action Discovery
 *
 * Visits every route and dynamically scans the rendered DOM for all
 * interactive controls: buttons, links, icons, FABs, dropdowns, tabs.
 *
 * Output:
 *   tests/reports/button-inventory.json   — full action inventory
 *   tests/reports/action-discovery-summary.md — human-readable summary
 *
 * Run:
 *   npx playwright test --project=action-discovery
 */

import { test } from '../fixtures/base';
import type { Page } from '@playwright/test';
import { ALL_ROUTES }   from '../helpers/routes';
import {
  DISCOVERY_SCRIPT,
  classifyAction,
  buildSelector,
  type RawElement,
  type DiscoveredAction,
} from '../helpers/action-discovery';
import { waitForPageLoad } from '../helpers/page-helpers';
import fs   from 'fs';
import path from 'path';

const BASE     = 'http://localhost:5173';
const OUT_DIR  = 'tests/reports';
const INV_FILE = path.join(OUT_DIR, 'button-inventory.json');

// ─── Types ────────────────────────────────────────────────────────────────────

interface InventoryEntry extends DiscoveredAction {
  discoveredAt: string;
}

interface Inventory {
  generated:    string;
  totalRoutes:  number;
  totalActions: number;
  byCategory:   Record<string, number>;
  byModule:     Record<string, number>;
  actions:      InventoryEntry[];
}

// ─── Discovery helpers ────────────────────────────────────────────────────────

async function discoverActionsOnPage(
  page: Parameters<typeof test>[1] extends (args: { page: infer P }) => unknown ? P : never,
  route: { path: string; module: string; name: string }
): Promise<InventoryEntry[]> {
  await page.goto(`${BASE}${route.path}`, { timeout: 25_000 }).catch(() => null);
  await waitForPageLoad(page).catch(() => null);

  // Allow async content to settle
  await page.waitForTimeout(500);

  let rawElements: RawElement[] = [];
  try {
    rawElements = await page.evaluate(DISCOVERY_SCRIPT) as RawElement[];
  } catch {
    return [];
  }

  const actions: InventoryEntry[] = [];

  for (const el of rawElements) {
    const { actionType, safetyCategory } = classifyAction(el);
    const { strategy, selector, text }   = buildSelector(el);

    actions.push({
      route:            route.path,
      module:           route.module,
      actionType,
      actionLabel:      el.label || el.text || '(unlabeled)',
      safetyCategory,
      selectorStrategy: strategy,
      selector,
      selectorText:     text,
      elementTag:       el.tag,
      elementClass:     el.className,
      discoveredAt:     new Date().toISOString(),
    });
  }

  return actions;
}

function buildSummary(inventory: Inventory): string {
  const now = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });

  const categoryRows = Object.entries(inventory.byCategory)
    .sort(([, a], [, b]) => b - a)
    .map(([cat, cnt]) => `| ${cat} | ${cnt} |`)
    .join('\n');

  const moduleRows = Object.entries(inventory.byModule)
    .sort(([, a], [, b]) => b - a)
    .map(([mod, cnt]) => `| ${mod} | ${cnt} |`)
    .join('\n');

  const safeCount      = inventory.actions.filter(a => a.safetyCategory === 'SAFE').length;
  const formCount      = inventory.actions.filter(a => a.safetyCategory === 'FORM').length;
  const approvalCount  = inventory.actions.filter(a => a.safetyCategory === 'APPROVAL').length;
  const dangerCount    = inventory.actions.filter(a => a.safetyCategory === 'DANGEROUS').length;
  const unknownCount   = inventory.actions.filter(a => a.safetyCategory === 'UNKNOWN').length;

  return `# Pulse ERP — Action Discovery Report
Generated: ${now} IST

## Summary

| Metric | Value |
|--------|-------|
| Routes scanned | ${inventory.totalRoutes} |
| Total actions discovered | ${inventory.totalActions} |
| SAFE (view/filter/export) | ${safeCount} |
| FORM (create/edit/save) | ${formCount} |
| APPROVAL (approve/reject) | ${approvalCount} |
| DANGEROUS (delete/purge) | ${dangerCount} |
| UNKNOWN | ${unknownCount} |

## By Safety Category

| Category | Count |
|----------|-------|
${categoryRows}

## By Module

| Module | Actions |
|--------|---------|
${moduleRows}

## Top Create Buttons (FORM actions)
${inventory.actions
  .filter(a => a.actionType === 'create-button')
  .slice(0, 20)
  .map(a => `- \`${a.route}\` → **${a.actionLabel}**`)
  .join('\n') || '— none found'}

## Top Dangerous Actions
${inventory.actions
  .filter(a => a.safetyCategory === 'DANGEROUS')
  .slice(0, 30)
  .map(a => `- \`${a.route}\` → **${a.actionLabel}** (${a.actionType})`)
  .join('\n') || '— none found'}

---
*Output: ${INV_FILE}*
*Generated by Pulse ERP Test Suite — Suite 09 Action Discovery*
`;
}

// ═════════════════════════════════════════════════════════════════════════════
// TESTS
// ═════════════════════════════════════════════════════════════════════════════

test('@P0 [ACTION-DISCOVERY] Scan all routes and build button inventory', async ({ page }: { page: Page }) => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.mkdirSync('tests/reports/screenshots', { recursive: true });

  const allActions: InventoryEntry[] = [];

  // Prioritize P0/P1 routes; still include P2 but lower priority
  const orderedRoutes = [
    ...ALL_ROUTES.filter(r => r.severity === 'P0'),
    ...ALL_ROUTES.filter(r => r.severity === 'P1'),
    ...ALL_ROUTES.filter(r => r.severity === 'P2'),
  ];

  let scannedCount = 0;

  for (const route of orderedRoutes) {
    try {
      const actions = await discoverActionsOnPage(page, route);
      allActions.push(...actions);
      scannedCount++;
      if (scannedCount % 10 === 0) {
        console.log(`  Scanned ${scannedCount}/${orderedRoutes.length} routes — ${allActions.length} actions so far`);
      }
    } catch (err) {
      console.warn(`  [WARN] Discovery failed for ${route.path}: ${err}`);
    }
  }

  // Build inventory object
  const byCategory: Record<string, number> = {};
  const byModule:   Record<string, number> = {};

  for (const a of allActions) {
    byCategory[a.safetyCategory] = (byCategory[a.safetyCategory] ?? 0) + 1;
    byModule[a.module]           = (byModule[a.module] ?? 0) + 1;
  }

  const inventory: Inventory = {
    generated:    new Date().toISOString(),
    totalRoutes:  scannedCount,
    totalActions: allActions.length,
    byCategory,
    byModule,
    actions: allActions,
  };

  fs.writeFileSync(INV_FILE, JSON.stringify(inventory, null, 2), 'utf8');

  const summary = buildSummary(inventory);
  fs.writeFileSync(path.join(OUT_DIR, 'action-discovery-summary.md'), summary, 'utf8');

  console.log(`\n✅ Action Discovery Complete`);
  console.log(`   Routes scanned:  ${scannedCount}`);
  console.log(`   Actions found:   ${allActions.length}`);
  console.log(`   SAFE:            ${byCategory['SAFE'] ?? 0}`);
  console.log(`   FORM:            ${byCategory['FORM'] ?? 0}`);
  console.log(`   APPROVAL:        ${byCategory['APPROVAL'] ?? 0}`);
  console.log(`   DANGEROUS:       ${byCategory['DANGEROUS'] ?? 0}`);
  console.log(`   Output:          ${INV_FILE}`);

  // Baseline assertion — we should find at least 50 actions
  const totalFound = allActions.length;
  if (totalFound < 50) {
    throw new Error(`Action discovery found only ${totalFound} actions — expected at least 50. Check if app is running.`);
  }
}, { timeout: 1_200_000 }); // 20 min budget for full scan

test('@P1 [ACTION-DISCOVERY] Verify inventory schema is valid', async () => {
  if (!fs.existsSync(INV_FILE)) {
    console.warn('  button-inventory.json not found — run action-discovery project first');
    return;
  }

  const raw  = fs.readFileSync(INV_FILE, 'utf8');
  const inv  = JSON.parse(raw) as Inventory;

  if (!inv.actions || !Array.isArray(inv.actions)) {
    throw new Error('button-inventory.json missing actions array');
  }

  const missingFields = inv.actions
    .slice(0, 50)
    .filter(a => !a.route || !a.module || !a.actionType || !a.safetyCategory || !a.selector);

  if (missingFields.length > 0) {
    throw new Error(`${missingFields.length} inventory entries missing required fields`);
  }

  console.log(`\n✅ Inventory schema valid — ${inv.totalActions} actions`);
});

test('@P1 [ACTION-DISCOVERY] Log module coverage gaps', async () => {
  if (!fs.existsSync(INV_FILE)) return;

  const inv  = JSON.parse(fs.readFileSync(INV_FILE, 'utf8')) as Inventory;
  const modulesWithCreate = new Set(
    inv.actions.filter(a => a.actionType === 'create-button').map(a => a.module)
  );
  const modulesWithDanger = new Set(
    inv.actions.filter(a => a.safetyCategory === 'DANGEROUS').map(a => a.module)
  );
  const allModules = [...new Set(ALL_ROUTES.map(r => r.module))];

  const noCreate  = allModules.filter(m => !modulesWithCreate.has(m));
  const noDanger  = allModules.filter(m => !modulesWithDanger.has(m));

  console.log(`\n📊 Module Coverage:`);
  console.log(`   ${modulesWithCreate.size}/${allModules.length} modules have CREATE buttons`);
  console.log(`   ${modulesWithDanger.size}/${allModules.length} modules have DANGEROUS buttons`);
  if (noCreate.length) console.log(`   Modules with no CREATE: ${noCreate.join(', ')}`);
  if (noDanger.length) console.log(`   Modules with no DELETE: ${noDanger.join(', ')}`);
});
